DEBUG = False

env = Environment(CPPPATH = ["."])

if DEBUG:
	env.Append(CXXFLAGS=["/std:c++20", "/Od", "/Zi", "/DEBUG", "/EHsc", "/fsanitize=address"])
	env.Append(LINKFLAGS=["/SUBSYSTEM:WINDOWS", "/DEBUG"])
else:
	env.Append(CXXFLAGS=["/std:c++20", "/Ox", "/EHsc"])
	env.Append(LINKFLAGS=["/SUBSYSTEM:WINDOWS"])

env.Append(LIBS=["user32", "dwmapi", "d2d1", "dwrite"])
env.Program("main", Glob("*.cpp") + Glob("controls/*.cpp"))